# Be sure to restart your server when you modify this file.

development:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_DEV"] %>

test:
  secret_key_base: <%= ENV["SECRET_KEY_BASE_TEST"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
